### ISSUE TITLE
Sysbot

### ISSUE THREAD

**Issue by hexbyt3** [easyworld/easyworld.github.com#1]
Hey easyworld!

I was wondering if you could please support discord for all of your bot upgrades. I would even pay you for them. I really would like multi trading please

**Comment by easyworld** [comment]
Multi trading in disord is theoretically supported, you can try it with my fork of SysBot.NET

**Comment by hexbyt3** [comment]
I’ll give it a try!  Is there a certain command I should run?

**Comment by easyworld** [comment]
I found that multi trading in discord need more code to support, but I'm not familiar with discord integration. https://github.com/Muchacho13Scripts/SysBot.NET maybe this fork will help you.

**Comment by hexbyt3** [comment]
I'm actually using that one right now, and unfortunately it's not set up for anyone to use.  It is set up for twitch subscribers only.

**Comment by hexbyt3** [comment]
He does however, have an AUTO OT feature in that fork which does work that is very nice.  But as far as his multi trade goes, it only works for twitch and he is still working on it from what he told me.

**Comment by easyworld** [comment]
My fork also have AUTO OT and multi trading, but only for Dodo and QQ. You can review my fork and do something modification for discord

**Comment by hexbyt3** [comment]
I’m not good at coding but I am going to try.

**Comment by hexbyt3** [comment]
I tried to find someone to pay to do it on Fiverr but they all said they couldn’t 😂
